import React from 'react'

export default function NFTPolicy () {
  
  return (
    <>
      <div className="font-sans p-10 mt-6 sm:mt-8 items-center">
        <h1 className="text-left font-bold italic text-xl lg:text-2xl xl:text-3xl mb-8 uppercase">Digital Assets Terms & Conditions</h1>
        <div className="mt-10 text-left font-sans leading-loose">
          <h1 className="italic mt-6 mb-5 font-bold uppercase text-lg lg:text-xl xl:text-2xl">Background</h1>
          <p className="mb-4 text-lg font-sans">
            MetaTed is a NFT (Non-Fungible Token) or digital artwork collection managed on the Solana network 
            to provide users with authentication and authorization features for applications built by MetaTed Labs LLC. 
            This website serves as an application allowing participants to utlize, view, and mint digital collectibles.
            Users are entirely responsible for the safety and management of their own private Solana wallets and validating all
            transactions and contracts generated by this website before approval. Moreover, smart contracts and utility applications run on
            the Solana network, so no ability to restore or undo any transactions.
          </p>
          <p className="mb-4 text-lg font-sans">
            Applications like this website, under the MetaTed Labs LLC hood, are provided &apos;as is&apos; and &apos;as available&apos;
            without warranty of any kind. By utilizing this website you are accepting sole responsibility for any and all transactions involving
            Metateds digital collectibles. However, MetaTed Labs LLC, does as much as possible to support or help any users who do have issues that
            we have the power to resolve.
          </p>
          <h1 className="italic mt-8 mb-3 font-bold uppercase text-lg lg:text-xl xl:text-2xl">OWNERSHIP</h1>

          <p className="mb-4 text-lg font-sans">
            A. Ownership of the MetaTed digital assets is provided to users who can cryptographically verify ownership or proof of authenticity of the MetaTed NFT, 
            which is fascilitated by a smart contract on the Solana network. In simple terms, you own the NFT if it is in your crypto wallet and can be
            authenticated and authorized by it! Moreover, ownership of the NFT is mediated entirely by the Smart Contract and the Solana network. At no point would we
            or can we modify the ownership of any MetaTed.
          </p>
          <p className="mb-1 text-lg font-sans">
            B. Personal use of digital assets is subject to your continued compliance with these Terms, which are as follows: 
          </p>
          <p className='text-lg pl-[22px]'>
            MetaTed Labs LLC grants royalty-free license to simply use and display the purchased Art
            solely for the following purposes:
          </p>
          <ul className="flex flex-col pl-8 mt-4 mb-6 list-disc leading-relaxed">
            <li className="font-sans list-item">
              For your own personal, non-commercial use.
            </li>
            <li className="font-sans list-item">
              In a marketplace that permits the purchase and sale of MetaTed NFT collections, or any third-party application, verified or validated by MetaTed Labs LLC 
              that handles transactions regarding NFTs provided that those applications cryptographically verifies each MetaTed owner&apos;s rights to 
              display the art for their Metated to ensure that only the actual owner can display the Art.
            </li> 
          </ul>
          <p className="mb-1 text-lg font-sans">
            C. Commercial use of digital assets is subject to your continued compliance with these Terms. MetaTed Labs LLC limited, partial license
            use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (&apos;Commercial Use&apos;). 
            Examples of limitations of Commercial Use is as follows:
          </p>
          <ul className="flex flex-col pl-8 mt-4 mb-6 list-disc leading-relaxed">
            <li className="font-sans list-item">
              Users cannot use the NFT Art to produce and sell merchandise products (Clothes etc.) 
              Unless the merchandise has been generated or copies of the art of has been displayed 
              using supported applications produced, verified, or validated by MetaTed Labs LLC.
              To be clear, these terms does not restrict you from the following:
              <ul className="flex flex-col pl-8 mt-4 mb-6 list-disc leading-relaxed">
                <li className="font-sans list-item">
                  Owning or operating a marketplace cryptographically verifies each MetaTed owner&apos;s rights
                  to display the art for their MetaTed to ensure that only the actual owner can display the art.
                </li>
                <li className="font-sans list-item">
                  Owning or operating a third party website or application that permits the inclusion, involvement, 
                  or participation of MetaTeds generally, provided that the third party website or application 
                  cryptographically verifies each MetaTed owner’s 
                  rights to display the art for their MetaTed assets 
                  to ensure that only the actual owner can display the art and is no longer visible once the owner disconnects from their wallet or leaves the website
                  or application or earning revenue from any of the foregoing.
                </li> 
              </ul>
            </li>
            
          </ul>
        </div>
      </div>
    </>
  )
}
